
title: Consciousness and Unambiguous Representations
descriptions: Thoughts about necessary physical correlates of phenomenal consciousness.
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  math_engine: mathjax