title: Consciousness and Unambiguous Representations
description: Thoughts and experiments about necessary physical correlates of phenomenal consciousness.
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

sass:
  sass_dir: assets/css